# --------------------------------------------------------------
#
#	gmake all
#	gmake install	 [install target in the XOP bin directory]
#	gmake clean	 [clean the source directory]
#	RJD, ANL, November 21, 2013
#
#
# --------------------------------------------------------------
#
# System definition (architecture)
#
# see https://stackoverflow.com/questions/17590525/correct-way-to-statically-link-in-gfortran-libraries-on-osx

ARCH = darwin

#
# flags for darwin
#
FC = gfortran
FFLAGS = 
FFLAGSD = -DDEBUG1 -g -m64
LDFLAGS =   -static-libgfortran -lgfortran -mmacosx-version-min=10.13
all:
	$(FC) $(FFLAGS) -c *.f
	ld -o xcom  -no_compact_unwind -arch x86_64 -macosx_version_min 10.13.0 -lSystem /usr/local/gfortran/lib/libgfortran.a /usr/local/gfortran/lib/libquadmath.a /usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/libgcc.a *.o

clean:
	rm -f *.o xcom
