ARCH = darwin

#
# flags for darwin
#
FC = gfortran
FFLAGS = 
all:
	$(FC) $(FFLAGS) -c IDPower.f95
	ld -o srcalc  -no_compact_unwind -arch x86_64 -macosx_version_min 10.13.0 -lSystem /usr/local/gfortran/lib/libgfortran.a /usr/local/gfortran/lib/libquadmath.a /usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0/libgcc.a IDPower.o

clean:
	rm -f *.o srcalc
